## Упражнения по библиотеке Numpy

In [1170]:
import math
import numpy as np
import itertools
from numpy import random as random

def get_random_arr(limit=20):
    size = (random.randint(1, limit), random.randint(1, limit))
    return random.randint(1, 20, size=size)

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [415]:
arr = get_random_arr()

condition = (arr > 3) & (arr < 8)
arr[condition] = -arr[condition]
arr

array([[-5, 15, -6, -5, 16, 13, -7, 18, 15, 19],
       [ 1, 17, -6, 18, -6, 19, 12,  8, 14, 11],
       [17,  1, 11,  8, 18, 12,  1, 19, 10, 14],
       [12, 16, 10, 13, 14,  1, 11, 10, -6, -4],
       [14, 10, 15, 11, 17, 18,  2, 14, 16,  1],
       [-5, 14, 18, 14, 19, 12,  9,  9, 17, -7],
       [-5, -5, 19, -4, 18, 17, 11, 17, 18, 10],
       [ 2, -7, 14, 16, 14, -4, -6, 19, 15, 10],
       [-6, -6, 14, 17, 12, -4, 17, 13, 18, 18]])

**2.** Заменить максимальный элемент случайного массива на 0

In [419]:
arr = get_random_arr()
max_value = np.max(arr)
arr[arr == max_value] = 0
arr

array([[13,  5, 18,  2,  7, 17,  7, 11,  9,  2, 17,  6, 18, 12,  4,  9,
         0],
       [ 0,  2,  6,  2,  8, 17,  6,  5,  3,  4, 10,  4, 18, 15, 10, 11,
        14],
       [ 1,  8, 18, 18,  4, 18, 12,  5,  9, 14,  7, 17, 10,  9, 18,  3,
         3],
       [ 5,  6,  9,  1,  5,  1,  1,  3,  9,  4,  2,  0, 17,  8, 17,  5,
        18],
       [ 2,  2, 13, 10, 18,  2,  7,  7, 15,  1, 13, 18,  9, 11, 14, 18,
        17],
       [17,  2,  9, 13, 13, 14,  9,  3, 16,  9, 15,  1, 13,  1, 14,  2,
         7],
       [ 0,  9, 13, 16,  0,  0,  4,  0,  0, 11,  8,  9,  7,  4, 14,  8,
         9],
       [15,  8, 15, 17, 14, 13, 11,  1, 13, 10,  7, 17,  7, 12, 17, 18,
         8],
       [ 0, 10, 17, 10,  6,  3,  7,  4,  4, 18,  4,  1,  7,  4,  4,  8,
         8],
       [ 2, 17, 17,  8, 13, 14, 10,  7,  2,  3,  3, 11, 18, 13,  1, 10,
        10],
       [ 4, 11,  8, 12, 10,  6, 18, 15,  0, 15, 15,  8, 13,  1,  3, 13,
        17],
       [ 4,  6, 15, 11,  4,  7,  7,  3,  7,  8, 17, 13, 16, 11, 1

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [751]:
arr1 = get_random_arr(5)
arr2 = get_random_arr(5)
print('Array 1:')
print(arr1)
print('Array 2:')
print(arr2)

result = arr1.ravel()[:, None] * arr2.ravel()[None, :]
print('product:')
print(result)


Array 1:
[[ 7  9 15 17]
 [ 9  1 18 12]]
Array 2:
[[15  8  2  3]
 [16 17 19  8]]
product:
[[105  56  14  21 112 119 133  56]
 [135  72  18  27 144 153 171  72]
 [225 120  30  45 240 255 285 120]
 [255 136  34  51 272 289 323 136]
 [135  72  18  27 144 153 171  72]
 [ 15   8   2   3  16  17  19   8]
 [270 144  36  54 288 306 342 144]
 [180  96  24  36 192 204 228  96]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [771]:
a = random.randint(1, 10, (8, 3))
b = random.randint(1, 10, (2, 2))
print('Initial arrays: ', a, b, sep='\n\n')

condition1 = np.any(np.isin(a, b[0]), axis=1)
condition2 = np.any(np.isin(a, b[1]), axis=1)
conditions = condition1 & condition2
print('\nResult: \n')
print(a[conditions])

Initial arrays: 

[[4 1 9]
 [7 3 9]
 [1 3 8]
 [4 5 7]
 [3 3 3]
 [8 8 3]
 [9 9 8]
 [1 6 7]]

[[5 6]
 [6 9]]

Result: 

[[1 6 7]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [825]:
a = random.randint(1, 3, (10, 3))
print('initial array:\n', a)
condition = np.apply_along_axis(lambda row: len(np.unique(row)) > 1, axis=1, arr=a)
a[condition]

initial array:
 [[1 2 1]
 [1 1 1]
 [2 1 2]
 [2 1 1]
 [1 1 1]
 [1 1 2]
 [2 2 2]
 [1 2 2]
 [1 1 1]
 [1 1 2]]


array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 1],
       [1, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [864]:
a = random.randint(1, 3, (10, 3))
print('initial array:\n', a)

print('Result: ')
print(np.unique(a, axis=0))

initial array:
 [[2 2 2]
 [1 2 2]
 [2 1 2]
 [2 2 1]
 [1 2 2]
 [2 2 2]
 [2 2 2]
 [1 2 2]
 [1 2 1]
 [2 1 1]]
Result: 
[[1 2 1]
 [1 2 2]
 [2 1 1]
 [2 1 2]
 [2 2 1]
 [2 2 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [904]:
a = random.randint(0, 5, (5, 5))

# w/o NumPy
print("Matrix: \n", a)
product = 1
for i, row in enumerate(a):
    value = row[i]
    if value != 0:
        product *= value
print('Product: ', product)

# NumPy realization
d = np.diag(a)
result = np.prod(d[d != 0])
print('NumPy Product: ', result)

Matrix: 
 [[4 4 3 2 1]
 [0 1 2 0 1]
 [4 1 3 0 1]
 [1 2 0 1 3]
 [4 0 3 1 1]]
Product:  12
NumPy Product:  12


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [1058]:
x = random.randint(0, 5, (5))
y = random.randint(0, 5, (5))
# x = np.array([1, 2, 2, 4])
# y = np.array([4, 2, 1, 2])

print(f'Arrays: \n{x}\n\n{y}\n')

# w/o NumPy
def is_same_multiset(x, y):
    if len(x) != len(y):
        return False
    x.sort()
    y.sort()
    for i, e in enumerate(x):
        if e != y[i]:
            return False
    return True

result = is_same_multiset(x, y)
print('w/o NumPy result: ', result)

# NumPy realization
def is_same_multiset_numpy(x, y):
    # list of numbers, count of numbers
    x_nums, x_counts = np.unique(x, return_counts=True)
    y_nums, y_counts = np.unique(y, return_counts=True)
    if(np.shape(x_nums) != np.shape(y_nums)):
        return False
    if(np.any(x_nums != y_nums) or np.any(x_counts != y_counts)):
        return False
    return True

result = is_same_multiset_numpy(x, y)
print('NumPy result: ', result)

Arrays: 
[1 4 4 2 4]

[4 1 3 2 0]

w/o NumPy result:  False
NumPy result:  False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [1082]:
# x = random.randint(0, 5, (10))
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0, 9])

# w/o numpy
def max_after_zero(x):
    result = 0
    for i in range(1, len(x)):
        if x[i - 1] == 0 and x[i] > result:
            result = x[i]
    return result

print('result w/o NumPy: ')
print(max_after_zero(x))


# NumPy realization
def max_after_zero_numpy(x):
    curr = np.ones((1))
    curr = np.hstack((curr, x))
    # array of e == 0
    ind = curr == 0
    arr = x[ind[:-1]]
    return np.max(x[ind[:-1]])

print('NumPy result: ')
print(max_after_zero_numpy(x))

result w/o NumPy: 
4
NumPy result: 
4


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [1164]:
x = np.array([2, 2, 2, 2, 1, 1, 8, 8, 3, 3, 3, 3, 5, 5])

# w/o NumPy
def length_encoding(x):
    curr = x[0]
    count = 0
    counts = []
    numbers = [curr]
    for e in x:
        if e == curr:
            count += 1
        else:
            curr = e
            counts.append(count)
            numbers.append(e)
            count = 1
    counts.append(count)
    return (numbers, counts)

result = length_encoding(x)
print("Result w/o NumPy: ", result)

# NumPy realization:
def length_encoding_numpy(x):
    numbers, ind, count = np.unique(x, return_index=True, return_counts=True)
    numbers = numbers[np.argsort(ind)]
    count = count[np.argsort(ind)]
    return (numbers, count)

result = length_encoding_numpy(x)
print("Result with NumPy: ", result)
    

Result w/o NumPy:  ([2, 1, 8, 3, 5], [4, 2, 2, 4, 2])
Result with NumPy:  (array([2, 1, 8, 3, 5]), array([4, 2, 2, 4, 2]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [1183]:
x = random.randint(1, 6, (3, 2))
y = random.randint(1, 6, (3, 2))
print("Initial objects:\n")
print(x)
print(y, '\n')

# w/o NumPy
def euclidean_matrix(x, y):
    result_matr = list()
    for i in range(len(x)):
        curr_list = list()
        for j in range(len(y)):
            dist = 0
            for k in range(len(x[0])):
                dist += (x[i][k] - y[j][k]) ** 2
            curr_list.append(math.sqrt(dist))
        result_matr.append(curr_list)
    return result_matr
print("result: \n", euclidean_matrix(x, y))

# NumPy realization
def euclidean_matrix_numpy(x, y):
    result = np.sqrt(np.sum((x[:, np.newaxis] - y) ** 2, axis=-1))
    return result
print("result: \n", euclidean_matrix_numpy(x, y))


Initial objects:

[[4 2]
 [4 2]
 [2 2]]
[[5 2]
 [2 5]
 [1 5]] 

result: 
 [[1.0, 3.605551275463989, 4.242640687119285], [1.0, 3.605551275463989, 4.242640687119285], [3.0, 3.0, 3.1622776601683795]]
result: 
 [[1.         3.60555128 4.24264069]
 [1.         3.60555128 4.24264069]
 [3.         3.         3.16227766]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [170]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [161]:
# your code

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [162]:
# your code

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [163]:
# your code

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [164]:
# your code

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [165]:
# your code

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [166]:
# your code

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
# your code